name: Terraform Apply
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
    
    - name: Terraform Apply
      run: |
        terraform init
        terraform apply -auto-approve
    
    - name: Save Terraform State
      if: success()
      run: |
        mkdir -p terraform-state
        cp terraform.tfstate terraform-state/
    
    - name: Upload Terraform State
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state
        path: terraform-state/