name: Terraform Destroy
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  terraform_destroy:
    name: Terraform Destroy
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1
    
    - name: Try to find artifact
      run: ls -la

    - name: Download Terraform State
      uses: actions/download-artifact@v4
      with:
        name: artifact
        path: artifact.zip
    
    - name: Terraform Destroy
      run: |
        terraform init
        terraform destroy -auto-approve